### ISSUE TITLE
Move to PyO3 organization

### ISSUE THREAD

**Issue by messense** [PyO3/python3-dll-a#3]
- [x] Move repository
- [x] Keep @ravenexp as a collaborator of this repository
- [x] Add [`pyo3/admins`](https://crates.io/teams/github:pyo3:admins) to the owners of this crate on crates.io
- [x] Update related links, for example `repository` in `Cargo.toml`

**Comment by ravenexp** [comment]
I tried to move it myself, but apparently I need a permission to create new repositories under the @PyO3 organization.
Is there something like "move request"?

**Comment by messense** [comment]
@ravenexp Do you mind transfer it to me first, I'll then move to pyo3.

**Comment by ravenexp** [comment]
> @ravenexp Do you mind transfer it to me first, I'll then move to pyo3.

Done.

**Comment by messense** [comment]
Moved to pyo3, looks like you have collaborator access already.

@davidhewitt can you add  write access for `Admins` and `Maintainers` teams for this repository please? Thanks!

**Comment by ravenexp** [comment]
I have an issue with adding a `crates.io` owner. It says that `pyo/admins` and `github:pyo:admins` orgs do not exist.

**Comment by messense** [comment]
Is it because of `pyo/admins` missing a `3`, should be `pyo3/admins`.

**Comment by messense** [comment]
https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner

> The syntax for teams is currently `github:org:team` (see examples above). In order to invite a team as an owner one must be a member of that team.

Hmm, can you add me to owner first? I'll then add the team.

**Comment by konstin** [comment]
> @davidhewitt can you add write access for Admins and Maintainers teams for this repository please? Thanks!

Not him, but done

**Comment by ravenexp** [comment]
> Is it because of `pyo/admins` missing a `3`, should be `pyo3/admins`.

Sorry, I made those typos when writing the comment. I used `pyo3` and `PyO3` on `crates.io`.

[Error messages](https://i.imgur.com/y7SZ9xl.png)

**Comment by messense** [comment]
> In order to invite a team as an owner one must be a member of that team.

I think it's caused by this restriction of crates.io.

**Comment by ravenexp** [comment]
> > In order to invite a team as an owner one must be a member of that team.
> 
> I think it's caused by this restriction of crates.io.

I've added you as an owner.

**Comment by messense** [comment]
All done, thanks everyone!

**Comment by ravenexp** [comment]
> All done, thanks everyone!

You should also update the `CRATES_IO_TOKEN` secret for this repository.

**Comment by messense** [comment]
> You should also update the `CRATES_IO_TOKEN` secret for this repository.

Done.
