### ISSUE TITLE
Automate `stable_abi.txt` updates

### ISSUE THREAD

**Issue by messense** [PyO3/python3-dll-a#5]
We can create a cron workflow on GitHub Actions that updates `stable_abi.txt` via pull request automatically.

Resources:
1. https://github.com/marketplace/actions/create-pull-request

**Comment by messense** [comment]
It'd be nice if we can also update the stable abi exports count in `parse_stable_abi_txt` test case automatically to [avoid manual update](https://github.com/PyO3/python3-dll-a/commit/ae029989e66fb22099bfb4bcd50bbd8a5330219d).

**Comment by ravenexp** [comment]
These checks are not essential and were added in the early development stages to test _something_.
Now that `stable_abi.txt` is updated semi-automatically, they can be changed from `==` to `>=` or even commented out.
