### ISSUE TITLE
Support for 3.13?

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/python3-dll-a#69]
(Sorry, hit enter before filling in issue contents.)

Hit this trying to build for 3.13 windows in `pydantic-core`. https://github.com/pydantic/pydantic-core/actions/runs/9647647378/job/26606981597?pr=1340#step:6:237

I guess the complication here is the pre-release nature of 3.13. The approach we're taking in PyO3 is that the API and ABI are meant to be stable already, so I _think_ it's probably correct to add support here now, though open to opinions.

Side note: I hit this because of https://github.com/PyO3/maturin-action/issues/275, which drove me to build on an older Python version to avoid `cffi` incompatibility with 3.13. I _think_ that's why the 3.13 shared library is missing and we're generating an import lib.

**Comment by ravenexp** [comment]
It doesn't look difficult, because it basically relies on https://github.com/actions/setup-python to collect the Python shared libraries. I'll give it a try.

**Comment by davidhewitt** [comment]
Thank you! 🚀

**Comment by ravenexp** [comment]
> Thank you! 🚀

v0.2.10 is on [crates.io](https://crates.io/crates/python3-dll-a/0.2.10) now.
