### ISSUE TITLE
Generating import library for Python 3.13t free-threaded DLL

### ISSUE THREAD

**Issue by davidhewitt** [PyO3/python3-dll-a#80]
I think we might need a separate `python313t.def` as well as generation options for the free-threaded build.

My reason for thinking this: symbols like [`PyUnstable_Module_SetGIL`](https://github.com/python/cpython/blob/3afb639f39e89888194d8e74cc498c8da3a58d8e/Include/moduleobject.h#L104), which PyO3 does use, are only defined on the free-threaded build.

So I think we correspondingly might need to specifically generate a free-threaded import library? I'll try to find an example which doesn't work with the current setup.

**Comment by ravenexp** [comment]
Makes sense. I'll try to figure out if the GitHub actions we use support co-installing `3.13` and `3.13t` at the same time.

**Comment by davidhewitt** [comment]
Awesome, thanks! 

You might be interested in using https://github.com/Quansight-Labs/setup-python

Not sure about co installing but that fork does accept 3.13t as an install option.

**Comment by ravenexp** [comment]
> You might be interested in using https://github.com/Quansight-Labs/setup-python
> 
> Not sure about co installing but that fork does accept 3.13t as an install option.

Thanks for the pointer. Microsoft support is being [funny](https://github.com/actions/setup-python/issues/771#issuecomment-2490607417) as always.

**Comment by ravenexp** [comment]
The implementation is done, but I'd like someone to look at the new public API before updating the documentation.
Are stringly-typed ABI tags such as `"t"` good enough or would an enum be more convenient to use in `pyo3-build`? @davidhewitt
